version: '3.8'

volumes:
  mongodb_data_container: null
  vscode:

    null
networks:
  docker_network:

    null
x-common-variables: &common-variables USER_SERVICE_PORT=$USER_SERVICE_PORT
  USER_SERVICE_HOST=$USER_SERVICE_HOST LOGGER_SERVICE_PORT=$LOGGER_SERVICE_PORT
  BASE_URI=$BASE_URI DATABASE_NAME=$DATABASE_NAME
  TOKEN_EXPIRE_IN=$TOKEN_EXPIRE_IN JWT_SECRET=$JWT_SECRET
  MONGO_PORT=$MONGO_PORT DATABASE_NAME=$DATABASE_NAME
  DATABASE_USER=$DATABASE_USER DATABASE_PASSWORD=$DATABASE_PASSWORD
  MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
  MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: "mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $DATABASE_NAME
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - docker_network

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: docker-zookeeper
    restart: unless-stopped
    networks:
      - docker_network
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: docker-kafka
    restart: unless-stopped
    networks:
      - docker_network
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker-kafka
      KAFKA_ZOOKEEPER_CONNECT: docker-zookeeper:2181

  redis:
    image: redis:latest
    container_name: docker-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - /root/redis-data/production:/data
    networks:
      - docker_network

  gateway:
    build:
      context: . 
    container_name: "core"
    restart: always
    links:
      - mongo:mongo
      - user
    depends_on:
      - mongo
      - kafka
      - zookeeper
      - redis
      - user
    # environment: *common-variables
    env_file: .env
    networks:
      - docker_network
    ports:
      - 0.0.0.0:${PORT}:${PORT}

  user:
    build:
      context: ../user-service 
    container_name: "userservice"
    entrypoint: [ "sh", "./entrypoint.sh", "seed" ]
    restart: always
    # environment: *common-variables
    env_file: .env
    ports:
      - 0.0.0.0:${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    links:
      - mongo
    networks:
      - docker_network
    depends_on:
      - mongo
      - kafka
      - zookeeper
      - redis